### ISSUE TITLE
Types and functions should be in a namespace or consistently prefixed to avoid ODR violations

### ISSUE THREAD

**Issue by joka921** [google/s2geometry#386] opened 2024-10-07 09:43 UTC
Currently, the `S2` library is not wrapped in a namespace. Additionally, most of the class names contain "S2" somewhere in their name, but not all of them. In particular, there are types called `Decoder` and `Encoder` in the public namespace defined in `util/coding/coder.h`. This leads to one-definition-rule violations when S2 is linked together with other code that also uses classes of the same name (in fact I ran into such problems).

In my opinion, there are two possibilities to mitigate this problem:
1. Consistently use a namespace for everything inside `S2`.
2. Consistently use "S2" as a prefix, suffix, or infix of *all* names of type, i.e renaming the `Encoder` and `Decoder` classes to `S2Encoder` and `S2Decoder` or using a similar naming scheme.

Please let me know, which variant you would prefer, and whether I should prepare a PR or whether you want to fix this yourselves, as it probably would break existing code and would require adaptations in documentations etc.

**Comment by smcallis** [comment] 2024-10-07 16:25
Definitely on my radar but it's a larger refactoring than just the open source because we have many internal clients that would have to be ported, and it's never been a high enough priority to do it.

**Comment by jmr** [comment] 2024-10-25 13:47
We'll fix this ourselves.

**Comment by jmr** [comment] 2024-11-08 09:29
Duplicate of #68 .

**Closed by jmr** 2024-11-08 09:29 UTC
