### ISSUE TITLE
S2Builder troubles

### ISSUE THREAD

**Issue by kostinio** [google/s2geometry#44] opened 2018-08-20 17:24 UTC
I'm trying to deal with feature to eliminate self-intersections. As written in s2builder.h  
> //  - It can eliminate self-intersections by finding all edge pairs that cross
> //    and adding a new vertex at each intersection point. 

and

> // - Guaranteed minimum separation between edges and vertices other than
> //     their endpoints (similar to the goals of Iterated Snap Rounding).  In
> //     other words, edges that do not intersect in the output are guaranteed
> //     to have a minimum separation between them."

Therefore when I use a builder I expect that output will meet the requrements to data for s2loop. But edges intersect point appears in output twice. That data is incorrect for s2loop.
I have checked a property of SnapFunction "min_edge_vertex_separation" and it is non zero.
>  // 5. A "min_edge_vertex_separation", the guaranteed minimum distance
>  //    between edges and non-incident vertices in the output.  This is
>  //    generally a fraction of "snap_radius" where the fraction depends on
>  //    the snap function.

In example below I'm trying to build s2loop from square with crossing diagonals. Here are many excess options, but i tried them all to be sure.

https://pastebin.com/WBpgn6Vj

This code crashs on S2loop::Init
> /home/noscoper/s2geometry-master/src/s2/s2loop.cc:134 ERROR Edge 1 has duplicate vertex with edge 4
> /home/noscoper/s2geometry-master/src/s2/s2loop.cc:287 FATAL Check failed: IsValid() Signal: SIGABRT (Aborted)

What is wrong? Is it my missunderstood or bug?

**Comment by jmr** [comment] 2018-11-01 14:50
The problem isn't with `S2Builder`, it's that [`S2Loop` doesn't support repeated vertices](https://github.com/google/s2geometry/blob/b8c45b5d739fe0263fec3b5fd182bcd1e1ea0fea/src/s2/s2loop.h#L64).

The explanation from [`s2loop.h`](https://github.com/google/s2geometry/blob/b8c45b5d739fe0263fec3b5fd182bcd1e1ea0fea/src/s2/s2loop.h#L81):
```
// Note: The reason that duplicate vertices and intersecting edges are not
// allowed is that they make it harder to define and implement loop
// relationships, e.g. whether one loop contains another.  If your data does
// not satisfy these restrictions, you can use S2Builder to normalize it.
```

If you print `s2textformat::ToString(outPolyline)`, you'll get:
`57.3:-57.3, 57.3:57.3, 0:0, -57.3:-57.3, -57.3:57.3, 0:0, 57.3:-57.3`.

The output needs to be two `S2Loop`s.

Depending on what you're trying to do, you could use `s2builderutil::S2PolylineVectorLayer` or `S2PolygonLayer` with `S2PolygonLayer::Options(S2Builder::EdgeType::UNDIRECTED)`.

**Comment by jmr** [comment] 2018-11-05 17:34
I'll close this for now. Reopen it if you still have questions.

**Closed by jmr** 2018-11-05 17:34 UTC
